import csv
import os
from datetime import datetime


def log_trade(row, file):
    """
    Log a trade to CSV file. Creates file with header if it doesn't exist.

    Args:
        row: List of values to log
        file: Path to CSV file
    """
    # Define headers based on file type
    if "backtest" in file:
        headers = ["EntryTime", "Size", "EntryBar", "EntryPrice", "ExitBar", 
                   "ExitPrice", "PnL", "Duration"]
    else:  # live trades
        headers = ["Timestamp", "Side", "Quantity", "Price", "OrderID", "Status"]

    # Check if file exists to determine if we need to write headers
    file_exists = os.path.isfile(file)

    with open(file, "a", newline='') as f:
        writer = csv.writer(f)

        # Write header if file is new
        if not file_exists:
            writer.writerow(headers)

        writer.writerow(row)


def log_trade_detailed(trade_data, file="data/trade_analysis.csv"):
    """
    Log detailed trade analysis with indicators and rationale.
    
    Args:
        trade_data: Dict with keys like {
            'timestamp': datetime,
            'side': 'BUY'|'SELL',
            'entry_price': float,
            'quantity': float,
            'rsi': float,
            'sma': float,
            'reason': str,
            'risk_pct': float,
            'position_size': float
        }
        file: CSV file path for detailed logs
    """
    headers = [
        "Timestamp", "Side", "EntryPrice", "Quantity", "RSI", "SMA", 
        "Reason", "RiskPct", "PositionSize"
    ]
    
    file_exists = os.path.isfile(file)
    
    with open(file, "a", newline='') as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(headers)
        
        row = [
            trade_data.get('timestamp', ''),
            trade_data.get('side', ''),
            trade_data.get('entry_price', ''),
            trade_data.get('quantity', ''),
            trade_data.get('rsi', ''),
            trade_data.get('sma', ''),
            trade_data.get('reason', ''),
            trade_data.get('risk_pct', ''),
            trade_data.get('position_size', '')
        ]
        writer.writerow(row)


def log_signal(signal_data, file="logs/signals.csv"):
    """
    Log all signals generated by strategy (entry, exit, skipped).
    
    Args:
        signal_data: Dict with {
            'timestamp': datetime,
            'bar': int,
            'price': float,
            'signal': str,  # 'BUY', 'SELL', 'CLOSE_LONG', 'CLOSE_SHORT', 'NONE'
            'rsi': float,
            'sma': float,
            'reason': str,
            'position_status': str
        }
        file: CSV file path for signal logs
    """
    headers = [
        "Timestamp", "Bar", "Price", "Signal", "RSI", "SMA", 
        "Reason", "PositionStatus"
    ]
    
    file_exists = os.path.isfile(file)
    
    with open(file, "a", newline='') as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(headers)
        
        row = [
            signal_data.get('timestamp', ''),
            signal_data.get('bar', ''),
            signal_data.get('price', ''),
            signal_data.get('signal', ''),
            signal_data.get('rsi', ''),
            signal_data.get('sma', ''),
            signal_data.get('reason', ''),
            signal_data.get('position_status', '')
        ]
        writer.writerow(row)


def ensure_data_dir():
    """Ensure data and logs directories exist."""
    for directory in ['data', 'logs']:
        if not os.path.exists(directory):
            os.makedirs(directory)




